### ISSUE TITLE
swf2js

### ISSUE THREAD

**Issue by lovoror** [awayfl/playerglobal#10]
https://swf2js.com/
Same as awayfl.  But It has good performance.

**Comment by eXponenta** [comment]
Have you examples for this? i not found it and project died.
UPD.
I can't run a lot of our games. 
Performance is low.

**Comment by ivanpopelyshev** [comment]
@lovoror 
Thanks for noticing it! looking in obfuscated code.. ;)

**Comment by lovoror** [comment]
Yes.Performance is low.
So . I don't think It is a right direction to parse swf  ABC code to js. 
Maybe export swf to png texture atlas is a good choice.

Anyway,If you use js worker to parse abccode and export images, you can achieve better performance.

**Comment by lovoror** [comment]
@eXponenta @80prozent @ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
Maybe something like https://github.com/rocket-ua/FlashLib is enough for you? I dont know your case

Well, of course usage of atlases is good for small projects. In my case, there are 1000 swf's with many filters,masks and animations inside. Code can be translated to TS, but prerendered atlases do not help my case at all.

**Comment by lovoror** [comment]
Face the same problem as you, we have 10w+ code and 2000+ swf.
But now the performance of awayfl is too bad, and Chrome's memory usage exceeds 2G+.
Also hope to optimize as soon as possible.
What you are doing is a very challenging and meaningful work.

**Comment by ivanpopelyshev** [comment]
Im making converter for https://www.facebook.com/playthehousehold/ , we are releasing right now, but not in facebook yet. If your project is of the same scale, I can try to arrange b2b talks. My work will be published in a few months anyway. 

If you have your own AS3->TS  translator, and you really need only Flash API like Shumway, I can publish only that part, maybe next month?

**Comment by lovoror** [comment]
What is the solution for your game? If your solution has been verified by online games, we can have a b2b talk.
There are still many problems with Awayfl. I wanted to use it, but I found a big problem with its performance. It will may take more time to improve it.
The solution we currently want to adopt is AS->TS. Use pixijs for rendering, and we develop Flash API adaptation by ourselves.
I am also looking forward to your Flash API. When is it expected to be released?

**Comment by ivanpopelyshev** [comment]
Its not verified, we are only starting to move players from flash to this thing. Its covered by tests but of course every html5-flash solution has its own tests that usually dont work on others ;)

Both flash and html5 build exist at the same time, use same resources.

Also, do you use Stage3D? We dont have interface for it, that part of app you'll have to rewrite to pure pixi with special shaders suited for your game.

I can give you Flash API in two weeks maybe if you write me t.me/hackerham

**Comment by lovoror** [comment]
We didn’t use any stage3D features.
I can't send messages to you on Telegram.

"Sorry, you can only send messages to mutual contacts at the moment."

**Comment by ivanpopelyshev** [comment]
that means someone complained about you :) 
ok then give me your telegram link

**Comment by lovoror** [comment]
I just registered an hour ago.
(removed to avoid a spaming)
