### ISSUE TITLE
AwayFL Filters Disabled 

### ISSUE THREAD

**Issue by Kadajmasamune** [awayfl/playerglobal#23]
![image_2023-11-22_170536551](https://github.com/awayfl/playerglobal/assets/150000465/407cf1d0-967c-4bf6-a43d-ac4c434ed17f)

So this is how Cactus mccoy 2 looks like on AwayFL
The image is well pretty much not visible and I reckon this is because Filters are disabled. How can I enable filters on Awayfl ?

**Comment by n0samu** [comment]
Hi, I've implemented 2 new options in [AwayFL Embed](https://github.com/awayfl/away-player-embed)'s AWAY_EMBED_CFG configuration object: `enableBlends` and `enableFilters`. I may enable these by default in the future, but for now, you'll need to set those. Also, the issue should've been created there, not here.
